---
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: release-please
        name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: go

      - name: Checkout
        uses: actions/checkout@v4
        if: steps.release-please.outputs.release_created
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        if: steps.release-please.outputs.release_created
        with:
          go-version-file: go.mod

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: steps.release-please.outputs.release_created

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: steps.release-please.outputs.release_created

      - name: Run GoReleaser
        if: steps.release-please.outputs.release_created
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
